name: toggl_track
description: A CLI client for Toggl Track API
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
  http: ^1.4.0

dev_dependencies:
  lints: ^5.0.0

executables:
  toggl_track: toggl_track
